language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  # - "pypy"
  # - "pypy3"
env:
  - DJANGO="Django~=1.8.0"
  - DJANGO="Django~=1.9.0"
  - DJANGO="Django~=1.10.0"
  - DJANGO="Django~=1.11.0"

install:
  - pip install -U pip
  - if [[ $TRAVIS_PYTHON_VERSION == pypy* ]]; then pip install psycopg2cffi; fi
  - if [[ $TRAVIS_PYTHON_VERSION != pypy* ]]; then pip install psycopg2; fi
  - pip install $DJANGO

script:
  - python runtests.py

matrix:
  exclude:
  - env: DJANGO="Django~=1.9.0"
    python: "3.3"
  - env: DJANGO="Django~=1.9.0"
    python: "pypy3"
  - env: DJANGO="Django~=1.10.0"
    python: "3.3"
  - env: DJANGO="Django~=1.10.0"
    python: "pypy3"
  - env: DJANGO="Django~=1.11.0"
    python: "3.3"
  - env: DJANGO="Django~=1.11.0"
    python: "pypy3"
